spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jobhunt?serverTimezone=Asia/Shanghai
#    username: jobhunt
#    password: iT26kk5Yie677Pri
    username: root
    password: root
  redis:
    host: 192.168.106.130
#    host: 127.0.0.1
    port: 6379
    password: 123456
  servlet:
    multipart:
      max-file-size: 2MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义属性配置
venture:
  mysetting:
    #上传文件的保存路径
    upload-file-path: E:/project/upload/
#    upload-file-path: /usr/local/jobhuntimg/
server:
  servlet:
    session:
      timeout: 2d