
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/newjobhunt?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root
  devtools:
    restart:
     enabled: false
  redis:
    host: 114.132.169.56
#    host: 127.0.0.1
    port: 6379
    password: Aa1230.0
  servlet:
    multipart:
      max-file-size: 2MB
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义属性配置
venture:
  mysetting:
    #上传文件的保存路径
    upload-file-path: E:/project/upload/
    # upload-file-path: /usr/local/jobhuntimg/
server:
  servlet:
    session:
      timeout: 2d
  port: 8080